# Copyright (C) 2017-2019 Dremio Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
 
name: Trigger Crossbow build

on: workflow_dispatch

env:
  CROSSBOW_GITHUB_TOKEN: ${{ secrets.CROSSBOW_GITHUB_TOKEN }}
  ARCHERY_DEFAULT_BRANCH: 'master'
jobs:
  trigger-crossbow:
    name: Trigger Crossbow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'
          fetch-depth: 0
      - name: Install Conda
        run: |
          set -e
          echo ""
          echo "Installing Miniconda."
          MINICONDA_URL="https://repo.continuum.io/miniconda"
          MINICONDA_FILE="Miniconda3-py39_22.11.1-1-Linux-x86_64.sh"
          curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
          bash $MINICONDA_FILE -b
      - name: Configuring Conda
        run: |
          set -e
          echo ""
          echo "Configuring conda."
          source /home/runner/miniconda3/bin/activate root
          conda config --remove channels defaults
          conda config --add channels defaults
          conda config --add channels conda-forge
          conda config --set show_channel_urls true
      - name: Install packages
        run: |
          set -e
          source /home/runner/miniconda3/bin/activate root
          conda install -y \
          click \
          github3.py \
          jinja2 \
          jira \
          pygit2=1.5.0 \
          ruamel.yaml \
          setuptools_scm \
          toolz
      - name: Run Crossbow script
        run: |
          set -e
          pushd ..
          source /home/runner/miniconda3/bin/activate root
          git clone -b rel-2300 https://github.com/lriggs/arrow.git
          pip install -e arrow/dev/archery[crossbow] 
          echo GITHUB_WORKSPACE:$GITHUB_WORKSPACE
          echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          cd arrow-build
          echo pwd
          pwd
          archery crossbow --queue-path $GITHUB_WORKSPACE --queue-remote https://github.com/$GITHUB_REPOSITORY submit java-jars --job-prefix nightly
